-- =====================================================================
-- Stax - Migration 0005: seed the shared exercise library
-- =====================================================================
-- Idempotent: upserts on slug, so re-running refreshes the catalog
-- without changing ids or touching anyone's custom exercises.
-- =====================================================================

insert into public.exercises
  (slug, owner_id, name, primary_muscle, secondary_muscles, equipment, mechanic, pattern, is_unilateral, cue, created_by)
values
  ('barbell-bench-press', null, 'Barbell Bench Press', 'chest', array['triceps','shoulders']::text[], array['barbell','bench']::text[], 'compound', 'push', false, 'Shoulder blades pinned back, bar to mid-chest, drive through the floor.', null),
  ('incline-barbell-bench-press', null, 'Incline Barbell Bench Press', 'chest', array['shoulders','triceps']::text[], array['barbell','bench']::text[], 'compound', 'push', false, 'Bench ~30 degrees, bar to upper chest, elbows about 45 degrees.', null),
  ('flat-dumbbell-press', null, 'Flat Dumbbell Press', 'chest', array['triceps','shoulders']::text[], array['dumbbells','bench']::text[], 'compound', 'push', false, 'Lower for a deep stretch, press up and slightly together at the top.', null),
  ('incline-dumbbell-press', null, 'Incline Dumbbell Press', 'chest', array['shoulders','triceps']::text[], array['dumbbells','bench']::text[], 'compound', 'push', false, '30 to 45 degree incline, control the stretch, don''t clank the bells.', null),
  ('dumbbell-fly', null, 'Dumbbell Fly', 'chest', array['shoulders']::text[], array['dumbbells','bench']::text[], 'isolation', 'push', false, 'Soft elbows, hug a wide arc, feel the stretch across the chest.', null),
  ('cable-fly', null, 'Cable Fly', 'chest', array['shoulders']::text[], array['cables']::text[], 'isolation', 'push', false, 'Sweep hands together and squeeze, slight forward lean, constant tension.', null),
  ('low-to-high-cable-fly', null, 'Low-to-High Cable Fly', 'chest', array['shoulders']::text[], array['cables']::text[], 'isolation', 'push', false, 'Pulleys low, scoop up and in toward the upper chest.', null),
  ('machine-chest-press', null, 'Machine Chest Press', 'chest', array['triceps','shoulders']::text[], array['machines']::text[], 'compound', 'push', false, 'Handles at mid-chest height, press without shrugging up.', null),
  ('pec-deck', null, 'Pec Deck', 'chest', array[]::text[], array['machines']::text[], 'isolation', 'push', false, 'Elbows at chest height, squeeze the pads together, slow return.', null),
  ('push-up', null, 'Push-Up', 'chest', array['triceps','shoulders','abs']::text[], array[]::text[], 'compound', 'push', false, 'Body in a straight line, elbows ~45 degrees, full lockout.', null),
  ('incline-push-up', null, 'Incline Push-Up', 'chest', array['triceps','shoulders']::text[], array[]::text[], 'compound', 'push', false, 'Hands elevated, body straight, great for higher-rep volume.', null),
  ('chest-dip', null, 'Chest Dip', 'chest', array['triceps','shoulders']::text[], array[]::text[], 'compound', 'push', false, 'Lean forward, elbows flare slightly, deep stretch then drive up.', null),
  ('dumbbell-floor-press', null, 'Dumbbell Floor Press', 'chest', array['triceps']::text[], array['dumbbells']::text[], 'compound', 'push', false, 'Lie on the floor, elbows touch down, press up. Easy on the shoulders.', null),
  ('smith-machine-bench-press', null, 'Smith Machine Bench Press', 'chest', array['triceps','shoulders']::text[], array['smith_machine','bench']::text[], 'compound', 'push', false, 'Fixed bar path, lower to mid-chest, drive up evenly.', null),
  ('pull-up', null, 'Pull-Up', 'lats', array['biceps','back']::text[], array['pull_up_bar']::text[], 'compound', 'pull', false, 'Drive elbows to the ribs, chest to bar, control the descent.', null),
  ('chin-up', null, 'Chin-Up', 'lats', array['biceps']::text[], array['pull_up_bar']::text[], 'compound', 'pull', false, 'Supinated grip, lead with the chest, full hang at the bottom.', null),
  ('lat-pulldown', null, 'Lat Pulldown', 'lats', array['biceps','back']::text[], array['cables','machines']::text[], 'compound', 'pull', false, 'Pull the bar to the upper chest, drive elbows down, no torso swing.', null),
  ('wide-grip-pulldown', null, 'Wide-Grip Pulldown', 'lats', array['back']::text[], array['cables','machines']::text[], 'compound', 'pull', false, 'Wide grip, think elbows to pockets, squeeze the lats.', null),
  ('barbell-row', null, 'Barbell Row', 'back', array['lats','biceps']::text[], array['barbell']::text[], 'compound', 'pull', false, 'Hinge ~45 degrees, row to the lower ribs, keep a flat back.', null),
  ('pendlay-row', null, 'Pendlay Row', 'back', array['lats','biceps']::text[], array['barbell']::text[], 'compound', 'pull', false, 'Bar resets on the floor each rep, explosive pull, flat back.', null),
  ('one-arm-dumbbell-row', null, 'One-Arm Dumbbell Row', 'back', array['lats','biceps']::text[], array['dumbbells','bench']::text[], 'compound', 'pull', true, 'Brace a hand on the bench, row to the hip, no torso rotation.', null),
  ('seated-cable-row', null, 'Seated Cable Row', 'back', array['lats','biceps']::text[], array['cables']::text[], 'compound', 'pull', false, 'Tall chest, pull to the belly, squeeze the shoulder blades.', null),
  ('t-bar-row', null, 'T-Bar Row', 'back', array['lats','biceps']::text[], array['barbell']::text[], 'compound', 'pull', false, 'Chest up, drive the elbows back, control the stretch.', null),
  ('chest-supported-row', null, 'Chest-Supported Row', 'back', array['lats','biceps']::text[], array['machines','dumbbells']::text[], 'compound', 'pull', false, 'Let the pad kill momentum, row purely with the back.', null),
  ('single-arm-cable-row', null, 'Single-Arm Cable Row', 'back', array['lats','biceps']::text[], array['cables']::text[], 'compound', 'pull', true, 'Row to the hip, let the shoulder stretch forward, no twisting.', null),
  ('straight-arm-pulldown', null, 'Straight-Arm Pulldown', 'lats', array[]::text[], array['cables']::text[], 'isolation', 'pull', false, 'Soft elbows fixed, sweep the bar to the thighs, feel the lats.', null),
  ('inverted-row', null, 'Inverted Row', 'back', array['lats','biceps']::text[], array[]::text[], 'compound', 'pull', false, 'Body rigid, pull the chest to the bar, squeeze at the top.', null),
  ('dumbbell-pullover', null, 'Dumbbell Pullover', 'lats', array['chest']::text[], array['dumbbells','bench']::text[], 'isolation', 'pull', false, 'Stretch overhead, pull back over with the lats, hips low.', null),
  ('barbell-shrug', null, 'Barbell Shrug', 'traps', array[]::text[], array['barbell']::text[], 'isolation', 'pull', false, 'Shrug straight up toward the ears, pause, no rolling.', null),
  ('dumbbell-shrug', null, 'Dumbbell Shrug', 'traps', array[]::text[], array['dumbbells']::text[], 'isolation', 'pull', false, 'Elevate the shoulders, hold a beat at the top.', null),
  ('face-pull', null, 'Face Pull', 'shoulders', array['traps','back']::text[], array['cables']::text[], 'isolation', 'pull', false, 'Pull the rope to the forehead, elbows high, externally rotate.', null),
  ('reverse-pec-deck', null, 'Reverse Pec Deck', 'shoulders', array['traps']::text[], array['machines']::text[], 'isolation', 'pull', false, 'Lead with the pinkies, squeeze the rear delts, slow return.', null),
  ('dumbbell-rear-delt-fly', null, 'Dumbbell Rear Delt Fly', 'shoulders', array['traps']::text[], array['dumbbells']::text[], 'isolation', 'pull', false, 'Hinge over, soft elbows, raise wide, no momentum.', null),
  ('band-pull-apart', null, 'Band Pull-Apart', 'shoulders', array['traps','back']::text[], array['bands']::text[], 'isolation', 'pull', false, 'Arms straight, pull the band apart to the chest, squeeze.', null),
  ('overhead-press', null, 'Overhead Barbell Press', 'shoulders', array['triceps']::text[], array['barbell','rack']::text[], 'compound', 'push', false, 'Brace hard, press the bar over the crown, ribs down.', null),
  ('dumbbell-shoulder-press', null, 'Dumbbell Shoulder Press', 'shoulders', array['triceps']::text[], array['dumbbells','bench']::text[], 'compound', 'push', false, 'Press up and slightly in, full lockout, don''t bang the bells.', null),
  ('arnold-press', null, 'Arnold Press', 'shoulders', array['triceps']::text[], array['dumbbells','bench']::text[], 'compound', 'push', false, 'Rotate the palms out as you press, control the rotation back.', null),
  ('machine-shoulder-press', null, 'Machine Shoulder Press', 'shoulders', array['triceps']::text[], array['machines']::text[], 'compound', 'push', false, 'Handles at shoulder height, press without leaning back.', null),
  ('dumbbell-lateral-raise', null, 'Dumbbell Lateral Raise', 'shoulders', array[]::text[], array['dumbbells']::text[], 'isolation', 'push', false, 'Lead with the elbows, raise to shoulder height, no swing.', null),
  ('cable-lateral-raise', null, 'Cable Lateral Raise', 'shoulders', array[]::text[], array['cables']::text[], 'isolation', 'push', true, 'Constant tension, raise across the body to shoulder height.', null),
  ('band-lateral-raise', null, 'Band Lateral Raise', 'shoulders', array[]::text[], array['bands']::text[], 'isolation', 'push', false, 'Stand on the band, raise to shoulder height, control down.', null),
  ('dumbbell-front-raise', null, 'Dumbbell Front Raise', 'shoulders', array[]::text[], array['dumbbells']::text[], 'isolation', 'push', false, 'Raise to eye level, control the lowering, no rocking.', null),
  ('upright-row', null, 'Upright Row', 'shoulders', array['traps']::text[], array['barbell']::text[], 'compound', 'pull', false, 'Pull to chest height, elbows lead, keep the bar close.', null),
  ('barbell-curl', null, 'Barbell Curl', 'biceps', array['forearms']::text[], array['barbell']::text[], 'isolation', 'pull', false, 'Elbows pinned, curl without swinging, squeeze at the top.', null),
  ('dumbbell-curl', null, 'Dumbbell Curl', 'biceps', array['forearms']::text[], array['dumbbells']::text[], 'isolation', 'pull', false, 'Supinate as you curl, control the lowering.', null),
  ('hammer-curl', null, 'Hammer Curl', 'biceps', array['forearms']::text[], array['dumbbells']::text[], 'isolation', 'pull', false, 'Neutral grip, elbows still, target the brachialis.', null),
  ('incline-dumbbell-curl', null, 'Incline Dumbbell Curl', 'biceps', array[]::text[], array['dumbbells','bench']::text[], 'isolation', 'pull', false, 'Arms hang back for a big stretch, curl without moving the elbows.', null),
  ('preacher-curl', null, 'Preacher Curl', 'biceps', array[]::text[], array['machines','dumbbells']::text[], 'isolation', 'pull', false, 'Upper arms flat on the pad, full stretch, no bouncing.', null),
  ('cable-curl', null, 'Cable Curl', 'biceps', array['forearms']::text[], array['cables']::text[], 'isolation', 'pull', false, 'Constant tension, elbows fixed, squeeze hard at the top.', null),
  ('concentration-curl', null, 'Concentration Curl', 'biceps', array[]::text[], array['dumbbells']::text[], 'isolation', 'pull', true, 'Elbow braced on the thigh, peak contraction each rep.', null),
  ('band-biceps-curl', null, 'Band Biceps Curl', 'biceps', array['forearms']::text[], array['bands']::text[], 'isolation', 'pull', false, 'Stand on the band, curl with constant tension, elbows fixed.', null),
  ('close-grip-bench-press', null, 'Close-Grip Bench Press', 'triceps', array['chest','shoulders']::text[], array['barbell','bench']::text[], 'compound', 'push', false, 'Hands shoulder-width, elbows tucked, bar to the lower chest.', null),
  ('triceps-pushdown', null, 'Triceps Pushdown', 'triceps', array[]::text[], array['cables']::text[], 'isolation', 'push', false, 'Elbows glued to the sides, full lockout, control the return.', null),
  ('rope-pushdown', null, 'Rope Pushdown', 'triceps', array[]::text[], array['cables']::text[], 'isolation', 'push', false, 'Spread the rope at the bottom, squeeze the triceps.', null),
  ('overhead-cable-extension', null, 'Overhead Cable Extension', 'triceps', array[]::text[], array['cables']::text[], 'isolation', 'push', false, 'Lean in, extend overhead, keep elbows narrow for the long head.', null),
  ('skullcrusher', null, 'EZ-Bar Skullcrusher', 'triceps', array[]::text[], array['barbell','bench']::text[], 'isolation', 'push', false, 'Lower to the forehead, elbows pointed up, extend fully.', null),
  ('dumbbell-overhead-extension', null, 'Dumbbell Overhead Extension', 'triceps', array[]::text[], array['dumbbells']::text[], 'isolation', 'push', false, 'Deep stretch behind the head, elbows narrow, full lockout.', null),
  ('triceps-dip', null, 'Triceps Dip', 'triceps', array['chest','shoulders']::text[], array[]::text[], 'compound', 'push', false, 'Stay upright, elbows back, lower to ~90 degrees and press up.', null),
  ('bench-dip', null, 'Bench Dip', 'triceps', array['shoulders']::text[], array['bench']::text[], 'compound', 'push', false, 'Hands on the bench, drop the hips down, press through the palms.', null),
  ('dumbbell-kickback', null, 'Dumbbell Kickback', 'triceps', array[]::text[], array['dumbbells']::text[], 'isolation', 'push', true, 'Upper arm parallel to the floor, extend back, squeeze.', null),
  ('wrist-curl', null, 'Wrist Curl', 'forearms', array[]::text[], array['dumbbells']::text[], 'isolation', 'pull', false, 'Forearms on the thighs, curl the wrists up through a full range.', null),
  ('reverse-curl', null, 'Reverse Curl', 'forearms', array['biceps']::text[], array['barbell']::text[], 'isolation', 'pull', false, 'Overhand grip, curl without swinging, target the forearms.', null),
  ('back-squat', null, 'Barbell Back Squat', 'quads', array['glutes','hamstrings']::text[], array['barbell','rack']::text[], 'compound', 'squat', false, 'Brace, sit between the hips, drive the floor away, knees track the toes.', null),
  ('front-squat', null, 'Front Squat', 'quads', array['glutes','abs']::text[], array['barbell','rack']::text[], 'compound', 'squat', false, 'Elbows high, upright torso, sit straight down.', null),
  ('leg-press', null, 'Leg Press', 'quads', array['glutes','hamstrings']::text[], array['machines']::text[], 'compound', 'squat', false, 'Feet shoulder-width, lower to ~90 degrees, don''t lock out hard.', null),
  ('hack-squat', null, 'Hack Squat', 'quads', array['glutes']::text[], array['machines']::text[], 'compound', 'squat', false, 'Full depth, push through the whole foot, controlled descent.', null),
  ('goblet-squat', null, 'Goblet Squat', 'quads', array['glutes']::text[], array['dumbbells']::text[], 'compound', 'squat', false, 'Hold the bell at the chest, sit tall and deep, elbows inside the knees.', null),
  ('smith-machine-squat', null, 'Smith Machine Squat', 'quads', array['glutes']::text[], array['smith_machine']::text[], 'compound', 'squat', false, 'Feet slightly forward, sit down the fixed path, full depth.', null),
  ('leg-extension', null, 'Leg Extension', 'quads', array[]::text[], array['machines']::text[], 'isolation', 'squat', false, 'Squeeze at the top, control down, don''t swing the weight.', null),
  ('walking-lunge', null, 'Walking Lunge', 'quads', array['glutes','hamstrings']::text[], array['dumbbells']::text[], 'compound', 'lunge', true, 'Long stride, drop the back knee, push through the front heel.', null),
  ('bulgarian-split-squat', null, 'Bulgarian Split Squat', 'quads', array['glutes']::text[], array['dumbbells','bench']::text[], 'compound', 'lunge', true, 'Rear foot elevated, drop straight down, weight on the front leg.', null),
  ('dumbbell-step-up', null, 'Dumbbell Step-Up', 'quads', array['glutes']::text[], array['dumbbells','bench']::text[], 'compound', 'lunge', true, 'Full foot on the box, drive through the heel, control down.', null),
  ('reverse-lunge', null, 'Reverse Lunge', 'quads', array['glutes']::text[], array['dumbbells']::text[], 'compound', 'lunge', true, 'Step back, drop the knee, push through the front heel to stand.', null),
  ('romanian-deadlift', null, 'Romanian Deadlift', 'hamstrings', array['glutes','back']::text[], array['barbell']::text[], 'compound', 'hinge', false, 'Soft knees, push the hips back, bar close, feel the hamstring stretch.', null),
  ('dumbbell-rdl', null, 'Dumbbell Romanian Deadlift', 'hamstrings', array['glutes']::text[], array['dumbbells']::text[], 'compound', 'hinge', false, 'Hinge at the hips, flat back, bells glide down the thighs.', null),
  ('lying-leg-curl', null, 'Lying Leg Curl', 'hamstrings', array[]::text[], array['machines']::text[], 'isolation', 'hinge', false, 'Curl the heels to the glutes, control down, hips on the pad.', null),
  ('seated-leg-curl', null, 'Seated Leg Curl', 'hamstrings', array[]::text[], array['machines']::text[], 'isolation', 'hinge', false, 'Drive the heels under the seat, full squeeze, slow return.', null),
  ('nordic-curl', null, 'Nordic Hamstring Curl', 'hamstrings', array[]::text[], array[]::text[], 'isolation', 'hinge', false, 'Anchor the ankles, lower as slowly as possible, stay rigid.', null),
  ('good-morning', null, 'Good Morning', 'hamstrings', array['glutes','back']::text[], array['barbell','rack']::text[], 'compound', 'hinge', false, 'Bar on the back, hinge with a flat back, feel the hamstrings.', null),
  ('hip-thrust', null, 'Barbell Hip Thrust', 'glutes', array['hamstrings']::text[], array['barbell','bench']::text[], 'compound', 'hinge', false, 'Upper back on the bench, chin tucked, drive hips to full lockout.', null),
  ('glute-bridge', null, 'Glute Bridge', 'glutes', array['hamstrings']::text[], array[]::text[], 'compound', 'hinge', false, 'Squeeze the glutes to lift, pause at the top, ribs down.', null),
  ('cable-glute-kickback', null, 'Cable Glute Kickback', 'glutes', array[]::text[], array['cables']::text[], 'isolation', 'hinge', true, 'Drive the heel back and up, squeeze, no lower-back arch.', null),
  ('sumo-deadlift', null, 'Sumo Deadlift', 'glutes', array['hamstrings','back']::text[], array['barbell']::text[], 'compound', 'hinge', false, 'Wide stance, grip inside the knees, push the floor apart.', null),
  ('conventional-deadlift', null, 'Conventional Deadlift', 'back', array['glutes','hamstrings']::text[], array['barbell']::text[], 'compound', 'hinge', false, 'Bar over mid-foot, flat back, push the floor away and stand tall.', null),
  ('standing-calf-raise', null, 'Standing Calf Raise', 'calves', array[]::text[], array['machines']::text[], 'isolation', 'other', false, 'Full stretch at the bottom, rise onto the toes, pause up top.', null),
  ('seated-calf-raise', null, 'Seated Calf Raise', 'calves', array[]::text[], array['machines']::text[], 'isolation', 'other', false, 'Knees bent, drive through the balls of the feet, slow stretch.', null),
  ('leg-press-calf-raise', null, 'Leg Press Calf Raise', 'calves', array[]::text[], array['machines']::text[], 'isolation', 'other', false, 'Toes on the platform edge, press through, full range.', null),
  ('dumbbell-calf-raise', null, 'Dumbbell Calf Raise', 'calves', array[]::text[], array['dumbbells']::text[], 'isolation', 'other', false, 'Hold a bell, rise onto the toes, stretch at the bottom.', null),
  ('hanging-leg-raise', null, 'Hanging Leg Raise', 'abs', array[]::text[], array['pull_up_bar']::text[], 'isolation', 'core', false, 'Dead hang, lift the legs with the abs, no swinging.', null),
  ('hanging-knee-raise', null, 'Hanging Knee Raise', 'abs', array[]::text[], array['pull_up_bar']::text[], 'isolation', 'core', false, 'Curl the knees up, posterior pelvic tilt, control down.', null),
  ('cable-crunch', null, 'Cable Crunch', 'abs', array[]::text[], array['cables']::text[], 'isolation', 'core', false, 'Crunch with the abs, round the spine, hips stay fixed.', null),
  ('plank', null, 'Plank', 'abs', array[]::text[], array[]::text[], 'isolation', 'core', false, 'Straight line head to heels, brace hard, squeeze the glutes.', null),
  ('crunch', null, 'Crunch', 'abs', array[]::text[], array[]::text[], 'isolation', 'core', false, 'Curl the ribs to the hips, exhale at the top, slow on the way down.', null),
  ('ab-wheel-rollout', null, 'Ab Wheel Rollout', 'abs', array[]::text[], array[]::text[], 'isolation', 'core', false, 'Brace, roll out as far as you can stay rigid, pull back with the abs.', null),
  ('russian-twist', null, 'Russian Twist', 'obliques', array['abs']::text[], array[]::text[], 'isolation', 'core', false, 'Lean back, rotate side to side, move from the trunk.', null),
  ('bicycle-crunch', null, 'Bicycle Crunch', 'abs', array['obliques']::text[], array[]::text[], 'isolation', 'core', false, 'Opposite elbow to knee, slow and controlled, full extension.', null)
on conflict (slug) do update set
  name = excluded.name,
  primary_muscle = excluded.primary_muscle,
  secondary_muscles = excluded.secondary_muscles,
  equipment = excluded.equipment,
  mechanic = excluded.mechanic,
  pattern = excluded.pattern,
  is_unilateral = excluded.is_unilateral,
  cue = excluded.cue;
